### ISSUE TITLE
options on setup are ignored

### ISSUE THREAD

**Issue by rudotriton** [ecthelionvi/NeoComposer.nvim#1]
i'm using lazy.nvim for setup and i'm trying to override a single keymap, however, neither lazy.nvim's  `opts` key nor calling neocomposer's `setup` in a `config` function seem to achieve it.

in both cases the plugin seems to already be set up and the setup function does an early return.

**Comment by ecthelionvi** [comment]
I think there might be an issue with how I'm handling the setup. Let me take a look.

**Comment by ecthelionvi** [comment]
Thank you for bringing this to my attention. I just updated the setup. I was not handling it properly. I apologize. It should be working correctly now.

**Comment by rudotriton** [comment]
no worries. however, there is another issue connected to this. i may be wrong, but it looks like you'd prefer your plugin to not need a `setup()` call by the user, i assume that's why there's `plugin/init.lua`. the specific issue the automatic setup creates for me is that i have a mapping under `<M-q>` which it overwrites. technically i can get around it by creating my mapping after neocomposer's setup. ultimately it's your call how you want your plugin to act, but perhaps some things to consider here around the design:

- it doesn't feel polite to overwrite the users' keymaps without them first having any say in it
- setting any non-default settings means an additional `setup()` call
- asking users to add `require("plugin").setup()` is already an established pattern
  - i think with something like lazy.nvim's `config = true` or `opts = {}` it's getting called anyway

**Comment by ecthelionvi** [comment]
I refactored the setup, as requested. Your settings should be saved. As far as the keymaps, you have made some valid points. The only keymap that I need to explicitly setup in the plugin is the toggle_record key as I need to filter that keymap from the recorded macro.

**Comment by ecthelionvi** [comment]
I had an idea for an interactive keymap setup wizard. Perhaps a command like :NeoComposerKeyamaps that the use call which will open an interactive buffer that you can edit with your desired keymaps.

**Comment by rudotriton** [comment]
thank you, i feel my concerns have been addressed
