### ISSUE TITLE
[FEAT REQ] `false` to disable keymap(s)

### ISSUE THREAD

**Issue by midrare** [ecthelionvi/NeoComposer.nvim#11]
This way, you can set your own keymaps instead of NeoComposer doing it for you. You can disable keymaps you don't need.

**Example:** 
```lua
require("NeoComposer").setup({
  keymaps = {
    play_macro = false,
    yank_macro = false,
    stop_macro = false,
    toggle_record = false,
  },
})

-- OR
require("NeoComposer").setup({
  keymaps = false
})
```

**Comment by ecthelionvi** [comment]
Good idea. Although I would have to leave the play_macro keymap because the lualine functionality depends on knowing the keymap.
