### ISSUE TITLE
"handle already closing", ui.lua:137

### ISSUE THREAD

**Issue by willothy** [ecthelionvi/NeoComposer.nvim#13]
This happens when using hydra.nvim - the window management hydra from the wiki more specifically. It may be as simple as calling `is_closing` to ensure it's not already closing before calling `close`. Happy to contribute a PR if that would be acceptable, just figured I'd create an issue first.

**Comment by ecthelionvi** [comment]
Thank you bringing this to my attention. I am open to you submitting a PR. 😃

**Comment by willothy** [comment]
> Thank you bringing this to my attention. I am open to you submitting a PR. smiley

Perfect! I'll get that in later today :)
