### ISSUE TITLE
The most recently recorded macro is not preselected

### ISSUE THREAD

**Issue by jakubgros** [ecthelionvi/NeoComposer.nvim#22]
Hello,

When I stop recording macro, it would be convenient to have a possibility to play it straightaway with the "play_macro" action. However, I noticed that the macro list is appended instead of prepended, so the newest macro ends up as the last one in the list. Is there any option to change this behavior?

**Comment by ecthelionvi** [comment]
In the config please set `queue_most_recent = true,`
