### ISSUE TITLE
Feature Request - Allow `status_recording()` text to have background colors to "none"

### ISSUE THREAD

**Issue by ls-devs** [ecthelionvi/NeoComposer.nvim#24]
Hi,
Actually when you display the status of `NeoComposer` in `Lualine`, you can customize the icon `foreground` and `background` colors but you can't modify the text colors near the icon.
It would be nice if we could modify them too.

Please see : (Here `RecordingSymbol` background color is set to `none` but the text isn't using this color.)
![image](https://github.com/ecthelionvi/NeoComposer.nvim/assets/58638832/22c10389-7f25-404e-b8c5-e622e34f1525)

**Comment by ecthelionvi** [comment]
Sorry, I've been busy with school. I'll take a crack at this over the weekend.

**Comment by ecthelionvi** [comment]
Sorry for the delay. I was able to add separate highlight groups for the text:

text_delay, text_play, and text_rec as well as a text_bg option. 

This will allow you to control the foreground and background of the text color separately from the symbols

**Comment by ls-devs** [comment]
Hey @ecthelionvi,
Don't worry for the delay and great job thank you !
Sorry to bother with this but there's still something happening after the text. I changed background of `RecordingText` to be `none` (transparent) and as you might see, on the far right of the text at the end, there's still some background color showing.
Please see : 
![image](https://github.com/ecthelionvi/NeoComposer.nvim/assets/58638832/82f09d6e-5a3a-44fe-904d-e32de8f32840)

**Comment by ecthelionvi** [comment]
Did you also change the text_bg color?

**Comment by ls-devs** [comment]
> Did you also change the text_bg color?

@ecthelionvi  I didn't. But I tried now to change `text_bg` and `text_rec` and I still got this : 
![image](https://github.com/ecthelionvi/NeoComposer.nvim/assets/58638832/279cef66-a355-485f-aed7-f22665cd2518)

**Comment by ls-devs** [comment]
@ecthelionvi  
I'm using [folke/tokyonight](https://github.com/folke/tokyonight.nvim)

**Comment by ecthelionvi** [comment]
The color to the right is the bg_dark color from tokyonight "#1e2030". NeoComposer is not setting that color to my understanding.

**Comment by ecthelionvi** [comment]
This will require further investigation 🤔

**Comment by ls-devs** [comment]
> This will require further investigation 🤔

@ecthelionvi After tweaking my configuration I can tell it only happens with NeoComposer.
It seems like there is an extra space at the end of the text and the `highlight` is not applying to it.

Can it be related to the way you setting up the highligh groups ? 
```lua
  if state.get_recording() then
    status = "%#RecordingSymbol#%*%#RecordingText# REC%*"
  elseif state.get_playing() then
    status = "%#PlayingSymbol#%*%#PlayingText# PLAY%*"
  end
```

Is there any other way to set the highlights groups ?

**Comment by ecthelionvi** [comment]
I figured out the issue. It has to do with Lualine padding. 

For example here is the default colorscheme with default padding of 1:

![4BF6B837-55E2-47BA-AE24-E4EE6A6E973B_4_5005_c](https://github.com/ecthelionvi/NeoComposer.nvim/assets/21297100/f7cc7548-196f-477b-b572-910c10ec9abe)

Here I changed the right padding to 0 and kept the left padding at 1:

![3D566DD1-0C51-4F01-99C4-EC8F037ED84D_4_5005_c](https://github.com/ecthelionvi/NeoComposer.nvim/assets/21297100/e7979fa8-8e17-41cf-b78b-696b6fbf8877)

**Comment by ls-devs** [comment]
@ecthelionvi Well done ! Removing both padding left and right resolve the issue 👍🏼 
Thanks for the help, very nice plugin you get there !
