### ISSUE TITLE
Frequent errors - on buffer open and during text editing

### ISSUE THREAD

**Issue by rqpt** [ecthelionvi/NeoComposer.nvim#6]
I'm not sure what could be causing this, but I get the following error semi-frequently:

```
Error executing vim.schedule lua callback: ...ack/packer/start/NeoComposer.nvim/lua/NeoComposer/ui.lua:137: handle 0x558caffc4660 is already closing
stack traceback:
        [C]: in function 'close'
        ...ack/packer/start/NeoComposer.nvim/lua/NeoComposer/ui.lua:137: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

The error occurs when opening large files sometimes or while editing text and performing operations. My pc is very low spec - I'm not sure if this is valuable info to mention or not. These errors do not occur when actively using features of the plugin, which seems strange to me.  

My plugin config:

```
require('NeoComposer').setup({
  delay_timer = '200',
  keymaps = {
    toggle_record = 'q',
    play_macro    = 'Q',
    stop_macro    = 'cq',
  },
  colors = {
    bg = 'StatusLine'
  }
})

vim.keymap.set('n', '<leader>eq', ':EditMacros<CR>')
vim.keymap.set('n', '<leader>qq', ':ToggleDelay<CR>')
```

**Comment by ecthelionvi** [comment]
Thank for the report. I'll do a deep dive and see what I can be done to fix the issue. Can you describe what is happening prior to the error?

**Comment by rqpt** [comment]
Awesome!  I have to commend you on your work with this plugin. It's quickly become one of my favourites.
